# =====================================================
# Laravel 開発環境の Docker Compose 定義
# Nginx + PHP-FPM + MariaDB + phpMyAdmin の4コンテナ構成
# =====================================================

# Docker Compose のバージョン指定 (v1.27以降は省略可能ですが、明示的に記述することを推奨)
# version: '3.8'  # 明示推奨
# =====================================================
# Docker Compose: Laravel + Nginx + PHP + MariaDB + phpMyAdmin
# =====================================================

services:
  nginx:
    build:
      context: ./docker-config/nginx
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      # - ./my-app:/var/www
      - ./my-app/agent:/var/www/agent
      - ./my-app/languages:/var/www/languages
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-config/errors:/var/log/nginx
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./docker-config/php
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-php
    volumes:
      # - ./my-app:/var/www
      - ./my-app/agent:/var/www/agent
      - ./my-app/languages:/var/www/languages
      - ./docker-config/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker-config/errors:/var/log/php-fpm
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${MARIADB_DATABASE}
      DB_USERNAME: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      TZ: ${TZ:-Asia/Tokyo}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mariadb:${MARIADB_VERSION:-10.11}
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-config/db/conf/my.conf:/etc/mysql/conf.d/my.conf
      - ./docker-config/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge
