# version: '3.8'

services:
  # ===============================
  # Nginx（Web サーバー）
  # ===============================
  nginx:
    build:
      context: ./docker-config/nginx            # Nginx用 Dockerfile のある場所
      dockerfile: Dockerfile                    # 使用する Dockerfile

    container_name: ${COMPOSE_PROJECT_NAME}-nginx

    ports:
      - "${NGINX_PORT:-8080}:80"                # ホストの8080 → コンテナの80番ポート

    volumes:
      - ./my-app:/var/www                       # Laravelアプリ全体（agent, language 等を含む）
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-config/errors:/var/log/nginx/errors

    depends_on:
      - php                                     # PHPコンテナが起動してからNginxを起動

    networks:
      - app-network

  # ===============================
  # PHP-FPM（Laravel実行エンジン）
  # ===============================
  php:
    build:
      context: ./docker-config/php              # PHP用 Dockerfile のある場所
      dockerfile: Dockerfile

    container_name: ${COMPOSE_PROJECT_NAME}-php

    volumes:
      - ./my-app:/var/www                       # Laravelアプリ全体をマウント
      - ./docker-config/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker-config/errors:/var/log/php-fpm/errors

    environment:
      DB_HOST: db                               # DB接続ホスト（サービス名）
      DB_PORT: 3306
      DB_DATABASE: ${MARIADB_DATABASE}          # 使用するDB名
      DB_USERNAME: ${MARIADB_USER}              # DBユーザー
      DB_PASSWORD: ${MARIADB_PASSWORD}          # DBパスワード
      TZ: ${TZ:-Asia/Tokyo}                     # タイムゾーン（デフォルトAsia/Tokyo）

    depends_on:
      - db

    networks:
      - app-network

  # ===============================
  # MariaDB（MySQL互換のデータベース）
  # ===============================
  db:
    build:
      context: ./docker-config/db/conf          # MariaDB用 Dockerfile のある場所
      dockerfile: Dockerfile

      args:
        MARIADB_VERSION: ${MARIADB_VERSION}     # MariaDB バージョン指定用ビルド引数

    # image: mariadb:${MARIADB_VERSION}         # 代替として直接指定も可能
    container_name: ${COMPOSE_PROJECT_NAME}-db

    restart: always                             # コンテナが落ちたら自動で再起動
    tty: true                                   # ターミナルログ有効（デバッグ用）

    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}

    volumes:
      - db-data:/var/lib/mysql                  # DBデータ永続化
      - ./docker-config/db/conf/my.conf:/etc/mysql/conf.d/my.conf  # MariaDB設定
      - ./docker-config/db/init:/docker-entrypoint-initdb.d        # 初期SQL実行用

    ports:
      - "3306:3306"                              # ホストからDB接続可（任意）

    networks:
      - app-network

  # ===============================
  # phpMyAdmin（DB管理ツール）
  # ===============================
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest         # 公式phpMyAdminイメージ
    platform: linux/amd64                       # Apple Silicon対策（ARM→x86）
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    restart: always

    environment:
      PMA_HOST: db                               # 接続対象DBホスト名（サービス名）
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"            # ホスト8081 → phpMyAdmin 80番

    depends_on:
      - db
      
    networks:
      - app-network

# ===============================
# データ永続化用ボリューム
# ===============================
volumes:
  db-data:
    driver: local

# ===============================
# サービス間通信用ネットワーク
# ===============================
networks:
  app-network:
    driver: bridge
